import React from "react";

const sizeClasses = {
  txtKarmaRegular24: "font-karma font-normal",
  txtInterRegular14Bluegray700: "font-inter font-normal",
  txtInterSemiBold24: "font-inter font-semibold",
  txtInterBold12AmberA200: "font-bold font-inter",
  txtMiSansBold69: "font-bold font-misans",
  txtInterMedium14Bluegray800: "font-inter font-medium",
  txtCardoBold32: "font-bold font-cardo",
  txtInterRegular25: "font-inter font-normal",
  txtRobotoRomanBold24: "font-bold font-roboto",
  txtInterRegular10: "font-inter font-normal",
  txtJejuHallasan40Indigo900: "font-jejuhallasan font-normal",
  txtJejuHallasan60: "font-jejuhallasan font-normal",
  txtInterRegular19: "font-inter font-normal",
  txtCardoItalic12: "font-cardo font-normal italic",
  txtCardoItalic14: "font-cardo font-normal italic",
  txtJejuHallasan40WhiteA700: "font-jejuhallasan font-normal",
  txtJejuHallasan30Blue900: "font-jejuhallasan font-normal",
  txtInterRegular14: "font-inter font-normal",
  txtInterRegular16: "font-inter font-normal",
  txtInterRegular17: "font-inter font-normal",
  txtKiwiMaruRegular24: "font-kiwimaru font-normal",
  txtInterExtraBold8: "font-extrabold font-inter",
  txtJejuHallasan56: "font-jejuhallasan font-normal",
  txtItimRegular48: "font-itim font-normal",
  txtJaldiRegular36: "font-jaldi font-normal",
  txtJejuHallasan50: "font-jejuhallasan font-normal",
  txtCardoItalic10: "font-cardo font-normal italic",
  txtJejuHallasan128: "font-jejuhallasan font-normal",
  txtCardoBold15: "font-bold font-cardo",
  txtJejuHallasan48Gray90002: "font-jejuhallasan font-normal",
  txtMiSansBold743: "font-bold font-misans",
  txtInterMedium14Gray900: "font-inter font-medium",
  txtRobotoBold48Gray90002: "font-bold font-roboto",
  txtMiSansBold5: "font-bold font-misans",
  txtMiSansBold4: "font-bold font-misans",
  txtJejuHallasan30Black900: "font-jejuhallasan font-normal",
  txtMiSansBold6: "font-bold font-misans",
  txtJejuHallasan42: "font-jejuhallasan font-normal",
  txtJejuHallasan45: "font-jejuhallasan font-normal",
  txtMiSansBold5Black9000a: "font-bold font-misans",
  txtJejuHallasan40: "font-jejuhallasan font-normal",
  txtJejuHallasan41: "font-jejuhallasan font-normal",
  txtRobotoRegular14: "font-normal font-roboto",
  txtRobotoRegular16: "font-normal font-roboto",
  txtMiSansBold731: "font-bold font-misans",
  txtRobotoMedium16WhiteA700: "font-medium font-roboto",
  txtJejuHallasan48: "font-jejuhallasan font-normal",
  txtRobotoRegular18: "font-normal font-roboto",
  txtInterMedium40: "font-inter font-medium",
  txtJejuHallasan110: "font-jejuhallasan font-normal",
  txtInterLight7: "font-inter font-light",
  txtRobotoRegular16WhiteA700: "font-normal font-roboto",
  txtCardoBold24: "font-bold font-cardo",
  txtJejuHallasan32: "font-jejuhallasan font-normal",
  txtMiSansNormal375: "font-misans font-normal",
  txtJejuHallasan28Gray90002: "font-jejuhallasan font-normal",
  txtInterBold22: "font-bold font-inter",
  txtJejuHallasan30: "font-jejuhallasan font-normal",
  txtRobotoBold40: "font-bold font-roboto",
  txtLexendExtraBold35: "font-extrabold font-lexend",
  txtInterBold20: "font-bold font-inter",
  txtMiSansBold527: "font-bold font-misans",
  txtJejuHallasan35: "font-jejuhallasan font-normal",
  txtJejuHallasan37: "font-jejuhallasan font-normal",
  txtInterExtraBold10: "font-extrabold font-inter",
  txtRobotoBold48: "font-bold font-roboto",
  txtJejuHallasan20Gray60001: "font-jejuhallasan font-normal",
  txtJejuHallasan50Gray90001: "font-jejuhallasan font-normal",
  txtInterRegular16Bluegray300: "font-inter font-normal",
  txtRobotoBold28: "font-bold font-roboto",
  txtJejuHallasan20: "font-jejuhallasan font-normal",
  txtInterMedium12: "font-inter font-medium",
  txtInterMedium16: "font-inter font-medium",
  txtRobotoRegular16Bluegray70002: "font-normal font-roboto",
  txtInterMedium14: "font-inter font-medium",
  txtInterBold12: "font-bold font-inter",
  txtMiSansBold69Black90087: "font-bold font-misans",
  txtJejuHallasan28: "font-jejuhallasan font-normal",
  txtJejuHallasan24Bluegray70002: "font-jejuhallasan font-normal",
  txtJejuHallasan24: "font-jejuhallasan font-normal",
  txtJejuHallasan25: "font-jejuhallasan font-normal",
  txtInterMedium20: "font-inter font-medium",
  txtJejuHallasan50Black900: "font-jejuhallasan font-normal",
  txtJejuHallasan130: "font-jejuhallasan font-normal",
  txtMiSansBold5Black90033: "font-bold font-misans",
  txtInterMedium12Bluegray800: "font-inter font-medium",
  txtRobotoMedium16: "font-medium font-roboto",
  txtJacquesFrancoisRegular28: "font-jacquesfrancois font-normal",
  txtJacquesFrancoisRegular26: "font-jacquesfrancois font-normal",
  txtJacquesFrancoisRegular24: "font-jacquesfrancois font-normal",
  txtJejuHallasan96: "font-jejuhallasan font-normal",
  txtJejuHallasan19: "font-jejuhallasan font-normal",
  txtInterSemiBold18Bluegray800: "font-inter font-semibold",
  txtKdamThmor24: "font-kdamthmor font-normal",
  txtRobotoMedium16Bluegray70002: "font-medium font-roboto",
  txtJejuHallasan15: "font-jejuhallasan font-normal",
  txtJejuHallasan16: "font-jejuhallasan font-normal",
  txtMiSansBold69Black900a2: "font-bold font-misans",
  txtJejuHallasan80: "font-jejuhallasan font-normal",
  txtKarlaRegular24: "font-karla font-normal",
  txtJacquesFrancoisRegular16: "font-jacquesfrancois font-normal",
  txtInterSemiBold18: "font-inter font-semibold",
  txtInterRegular25Black900: "font-inter font-normal",
  txtMiSansBold69Black90075: "font-bold font-misans",
  txtCourgetteRegular25: "font-courgette font-normal",
  txtRobotoBold16: "font-bold font-roboto",
  txtJejuHallasan40AmberA200: "font-jejuhallasan font-normal",
};

const Text = ({ children, className = "", size, as, ...restProps }) => {
  const Component = as || "p";

  return (
    <Component
      className={`text-left ${className} ${size && sizeClasses[size]}`}
      {...restProps}
    >
      {children}
    </Component>
  );
};

export { Text };
