import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">TelehealthOne</Link>
        </li>
        <li>
          <Link to="/aibot">AIBOT</Link>
        </li>
        <li>
          <Link to="/virtual">Virtual</Link>
        </li>
        <li>
          <Link to="/virtual20">Virtual20</Link>
        </li>
        <li>
          <Link to="/donationone">DonationOne</Link>
        </li>
        <li>
          <Link to="/donationtwo">DonationTwo</Link>
        </li>
        <li>
          <Link to="/donationthree">DonationThree</Link>
        </li>
        <li>
          <Link to="/telehealthtwo">TelehealthTwo</Link>
        </li>
        <li>
          <Link to="/premiumone">PremiumOne</Link>
        </li>
        <li>
          <Link to="/ebooksone">EbooksOne</Link>
        </li>
        <li>
          <Link to="/mainpage">MainPage</Link>
        </li>
        <li>
          <Link to="/template">Template</Link>
        </li>
        <li>
          <Link to="/community">Community</Link>
        </li>
        <li>
          <Link to="/moodmix">MoodMix</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
